name: lemniscate_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.19.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    flutter_svg: ^2.0.5
    go_router: ^11.1.2
    flutter_bloc: ^8.1.3
    equatable: ^2.0.5
    json_annotation: ^4.8.1
    copy_with_extension: ^5.0.2
    supabase_flutter: ^1.10.19
    flutter_dotenv: ^5.1.0
    intl: ^0.18.1
    timeago: ^3.5.0
    image_picker: ^1.0.4
    uuid: ^4.1.0

dev_dependencies:
    build_runner:
    flutter_test:
        sdk: flutter

    json_serializable: ^6.3.1
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/logos/
        - assets/images/icons/
        - .env

    fonts:
        - family: Nunito
          fonts:
              - asset: assets/fonts/Nunito-Regular.ttf
              - asset: assets/fonts/Nunito-Bold.ttf
              - asset: assets/fonts/Nunito-Light.ttf
              - asset: assets/fonts/Nunito-Medium.ttf
              - asset: assets/fonts/Nunito-Semibold.ttf
